# dataset
name: "cifar10"
x_dim: 3072  # 3 * 32 * 32
x_shape: [3, 32, 32]
patch_size: [4, 4]

# clustering
n_clusters: 10
param_q_init_cls: 1
temp_init_cls: 1.0
temp_decay_cls: 0.00001
temp_min_cls: 0.001

# quantization
book_size: 512
param_q_init: 20
temp_init: 1.0
temp_decay: 0.000001
temp_min: 0.001

# model
n_resblocks: 6
latent_dim: 64
latent_size: [8, 8]
nlayers: 6
nheads: 16
dropout: 0.1

# diffusion
noise_steps: 1000
beta_start: 0.0001
beta_end: 0.02
n_ditblocks: 6
nheads_dit: 16

# loss csqvae
lmd_lrc: 1
lmd_klc: 1
lmd_kld: 0.1
lmd_ldt: 0.0000000001
lmd_c_elbo: 0.1
lmd_c_real: 10

# loss diffusion
lmd_kld_diffusion: 1
lmd_ldt_diffusion: 1

# optim
n_labeled_samples: 50000
epochs_csqvae: 200
epochs_diffusion: 1000
lr_csqvae: 0.001
lr_diffusion: 0.0001
batch_size: 128
accumulate_grad_batches: 1
num_workers: 4
