# clustering
n_clusters: 10
param_q_cls_init: 1
temp_init_cls: 1.0
temp_decay_cls: 0.001
temp_min_cls: 0.0000000001

# quantization
param_q_init: 10
temp_init: 1.0
temp_decay: 0.00001
temp_min: 0.0000000001

# model
n_resblocks: 2
latent_ndim: 64
book_size: 128

# optim
lmd_lrc: 1
lmd_klc: 1
lmd_kld: 1
lmd_c_real: 1
lmd_c_prior: 1

lr: 0.001
lr_lmd: 0.95

# training
n_labeled_samples: 1000
epochs: 100
batch_size: 32
accumulate_grad_batches: 1
num_workers: 8
